export const projects = [
  {
    title: 'E-Services',
    description: "Management system for companies that perform technical services. Target audience: Companies that perform technical services such as electronic technical service, computer technical service, cell phone technical service, Auto body painting services. CRUD (Customers, work orders, budgets, products and services).",
    image: '/images/eservices.jpg',
    tags: ['Java', 'Spring', 'JWT', 'React', 'Next', 'MUI'],
    bss: 'Ampersand',
    source: 'https://github.com/GBergesio/esdiService',
    visit: 'https://drive.google.com/drive/folders/1G0wPLpkyrlJWkKBxQMRu3beuE-AT39X1',
    id: 0,
  },
  {
    title: 'Academium',
    description: "This is the startup project where I currently work. The project is designed for academies that need to manage their day to day.In the system you can create classes and events and assign students and teachers to them. CRUD (Teachers, Students, Suppliers, Products, Classes, Classrooms, Events).",
    image: '/images/academium.jpg',
    tags: ['React', 'Next', 'MUI'],
    bss: 'JuacaxDev',
    source: 'https://github.com/juacaxdev/juacaxDev/',
    visit: '#',
    id: 1,
  },
  {
    title: 'Portfolio Website',
    description: "This was my personal portfolio website that has all my work and project experience, including my resume. It used to be my main portfolio before deploying this current portfolio.",
    image: '/images/portfolio.jpg',
    bss: 'Personal Project',
    tags: ['HTML', 'CSS', 'Bootstrap', 'Javascript'],
    source: 'https://github.com/GBergesio/portfolio',
    visit: 'https://portfolio-gbergesio.vercel.app',
    id: 2,
  },
  {
    title: 'Kobe Store',
    description: "Kobe is an ecommerce specialized in anime and fiction merchandising. This store has email verification. You must be logged in to make a purchase. The store has an administration section with stock management, prices and massive price updates.",
    image: '/images/kobe.jpg',
    bss: 'MindHub Bootcamp',
    tags: ['JAVA', 'Spring', 'Javascript', 'Vue', 'Bootsrap'],
    source: 'https://github.com/GBergesio/Kobe-ecommerce',
    visit: 'https://kobestore.herokuapp.com/store/index.html',
    id: 3,
  },
  {
    title: 'Rune Homebanking',
    description: "Homebanking developed in the MindHub bootcamp. On the website you can create accounts, create credit and debit cards, make transfers and request loans.",
    image: '/images/homebanking.jpg',
    bss: 'MindHub Bootcamp',
    tags: ['JAVA', 'Spring', 'Javascript', 'Vue', 'Bootsrap'],
    source: 'https://github.com/GBergesio/homebanking-Rune',
    visit: 'https://runebank.herokuapp.com/web/index.html',
    id: 4,
  },
  {
    title: 'Franco Petshop',
    description: "Ecommerce developed for the first Mindhub bootcamp project.",
    image: '/images/petshop.jpg',
    tags: ['HTML', 'CSS', 'Javascript'],
    bss: 'MindHub Bootcamp',
    source: 'https://github.com/GBergesio/Web-Petshop',
    visit: 'https://gbergesio.github.io/Web-Petshop/',
    id: 5,
  },
  {
    title: 'Ecommerce - Alta Oferta',
    description: "This was the first project I developed. Store created for a company in my town, created with wordpress and elementor.The database connects to the store's ERP system.",
    image: '/images/esdi.jpg',
    tags: ['WordPress', 'Elementor'],
    bss: 'Electro Service - Alta Oferta',
    source: 'https://electro.altaoferta.com',
    visit: 'https://electro.altaoferta.com',
    id: 6,
  },

];

export const TimeLineData = [
  { year: '2021 August', text: 'I Started my journey as a new developer.', },
  { year: '2022 March', text: 'I started an intensive bootcamp.', },
  { year: '2022 July', text: 'I finished the bootcamp', },
  { year: '2022 July', text: 'I started my biggest personal web development project with JAVA + React', },
  { year: '2022 September', text: 'I started working as a React developer at a startup called JuacaxDev', },
  { year: '2023 March', text: 'I will start a degree in Systems', },
];